description: "Updated UnDraw library. These illustrations are designed by Katerina Limpitsouni."
name: "ms_undraw"
repository: "https://github.com/Marcus-Software/ms_undraw"
version: "4.1.0"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies: 
  flutter_svg: ">=2.0.17 <3.0.0"
  http: ">=1.3.0 <2.0.0"
  path_provider: ">=2.1.5 <3.0.0"
  flutter: 
    sdk: "flutter"

dev_dependencies:
  cli_util: "^0.4.2"
  yaml: ^3.1.3
  fhir_yaml: ^0.9.0
  flutter_test: 
    sdk: "flutter"
